src/Entity/Script.php
<?php

namespace App\Entity;
use App\Entity;
use Symfony\Component\Routing\Annotation;
use App\Service\ScriptMetrics;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ScriptRepository")
 */
class Script
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }


    /** 
    *@ORM\Column(type="integer", name="lines_per_actor", nullable=true, options={"unsigned":true, "default":0})
    */
    private $lines_per_actor;


    /** 
    *@ORM\Column(type="integer", name="words_per_actor", nullable=true, options={"unsigned":true, "default":0})
    */
    private $words_per_actor;


    /** 
    *@ORM\Column(type="integer", name="mentions_per_actor", nullable=true, options={"unsigned":true, "default":0})
    */
    private $mentions_per_actor;


    /** 
    *@ORM\Column(type="integer", name="movies_per_year", nullable=true, options={"unsigned":true, "default":0})
    */
    private $movies_per_year;

    /** 
    *@ORM\Column(type="integer", name="percent_of_fails", nullable=true, options={"unsigned":true, "default":0})
    */
    private $percent_of_fails;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $actor_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $company;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $actor_pay;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $actor_revenue;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $company_revenue;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $losses;


    //getters and setters

    //get id
    public function getId2() {
        return $this->id;
    }

    //get lines per actor 
    public function getLinesPerActor() {
        return $this->lines_per_actor;
    }
   
    //set lines per actor 
    public function setLinesPerActor($lines_per_actor) {
        return $this->lines_per_actor = $lines_per_actor;
    }


    //get words per actor  #todo build functionality for this 
    public function getWordsPerActor() {
        return $this->words_per_actor;
    }
   
    //set words per actor 
    public function setWordsPerActor($words_per_actor) {
        return $this->words_per_actor = $words_per_actor;
    }


    //get mentions per actor 
    public function getMentionsPerActor() {
        //this is where your regex should go for # of lines, something like /^/$actor_name.*$/
        return $this->mentions_per_actor;
    }
   
    //set mentions per actor 
    public function setMentionsPerActor($mentions_per_actor) {
        return $this->mentions_per_actor = $mentions_per_actor;
    }

    
    //get MoviesPerYear
    public function getMoviesPerYear() {
        return $this->movies_per_year;
    }

    //set MoviesPerYear
    public function setMoviesPerYear($movies_per_year) {
        return $this->movies_per_year = $movies_per_year;
    }

    //get percent of fails 
    public function getPercentOfFails() {
        return $this->percent_of_fails;
    }

    //set percent of fails
    public function setPercentOfFails($percent_of_fails) {
        return $this->percent_of_fails = $percent_of_fails;
    }

    //get and set script title
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    //get and set script body 
    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getActorName(): ?string
    {
        return $this->actor_name;
    }

    public function setActorName(?string $actor_name): self
    {
        $this->actor_name = $actor_name;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getActorPay(): ?int
    {
        return $this->actor_pay;
    }

    public function setActorPay(?int $actor_pay): self
    {
        $this->actor_pay = $actor_pay;

        return $this;
    }

    public function getActorRevenue(): ?int
    {
        return $this->actor_revenue;
    }

    public function setActorRevenue(?int $actor_revenue): self
    {
        $this->actor_revenue = $actor_revenue;

        return $this;
    }

    public function getCompanyRevenue(): ?int
    {
        return $this->company_revenue;
    }

    public function setCompanyRevenue(?int $company_revenue): self
    {
        $this->company_revenue = $company_revenue;

        return $this;
    }

    public function getLosses(): ?int
    {
        return $this->losses;
    }

    public function setLosses(?int $losses): self
    {
        $this->losses = $losses;

        return $this;
    }
}

templates/pages/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %} Add Movie Data {% endblock %}

{% block body %}

{{ form_start(form)}}
{{ form_widget(form)}}
{{ form_end(form)}}

<a href="/movies/">Go Back</a>

{% endblock %} 

templates/pages/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edit Movie Data {% endblock %}

{% block body %}

{{ form_start(form)}}
{{ form_widget(form)}}
{{ form_end(form)}}

<a href="/scripts_home/">Go Back</a>

{% endblock %} 

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Movie Titles{% endblock %}

{% block body %}
{% if ScriptTitles %}
    <table id="home" class="table table-striped">
        <thead>
            <tr>
                <th> Movies</th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td> Movie and Script info</td>
                      <td>  <a href="/scripts" class="btn btn-dark">Go</a> </td>
                     <td> Add a movie or script</td>
                    <td>
                        <a href="/add" class="btn btn-light">Go</a>
                    </td>
                </tr>
            </tbody>
    </table>
    {% else %}
        <p> No data to display. </p>
{% endif %}
{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/pages/script.html.twig
{% extends 'base.html.twig' %}

{% block title %} Scripts {% endblock %}

{% block body %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th> Title </th>
                <th> Company </th>
                <th> Character Name </th>
                <th> Actor Pay </th>
                <th> Actor Revenue </th>
                <th> Lines Per Script </th>
                <th> Words Per Script </th>
                <th> Actor Mentions</th>
                <th> Company Revenue </th>
                <th> Movies Per Year</th>
                <th> Percent Of Fails </th>
                <th> Losses </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ScriptTitles.title}}</td>
                <td>{{ScriptTitles.company}}</td>
                <td>{{ScriptTitles.actorName}}</td>
                <td>{{ScriptTitles.actorPay}}</td>
                <td>{{ScriptTitles.actorRevenue}}</td>
                <td>{{ScriptTitles.linesPerActor}}</td>
                <td>{{ScriptTitles.wordsPerActor}}</td>
                <td>{{ScriptTitles.mentionsPerActor}}</td>
                <td>{{ScriptTitles.companyRevenue}}</td>
                <td>{{ScriptTitles.moviesPerYear}}</td>
                <td>{{ScriptTitles.percentOfFails}}</td>
                <td>{{ScriptTitles.losses}}</td>
            </tr>
    </table>
    <a href="/scripts/">Go Back</a>

{% endblock %} 

templates/pages/script_admin.html.twig
{% extends 'base.html.twig' %}

{% block title %} Add Script Data {% endblock %}

{% block body %}

{{ form_start(form)}}
{{ form_widget(form)}}
{{ form_end(form)}}

<a href="/scripts/">Go Back</a>

{% endblock %} 

templates/pages/scripts_home.html.twig
{% extends 'base.html.twig' %}

{% block title %} Movie Scripts{% endblock %}

{% block body %}
{% if ScriptTitles %}
    <table id="scripts" class="table table-striped">
        <thead>
            <tr>
                <th> Movie Script</th>
            </tr>
        </thead>
        <tbody>
            {% for ScriptTitle in ScriptTitles %}
                <tr>
                    <td> {{ ScriptTitle.id }}</td>
                    <td> {{ ScriptTitle.title }}</td>
                    <td>
                        <a href="/script/{{ ScriptTitle.id }}" class="btn btn-dark">Info</a>
                        <a href="/script/edit/{{ ScriptTitle.id }}" class="btn btn-light">Edit</a>
                        <a href="/scripts/delete/{{ ScriptTitle.id }}" id="delete" class="btn btn-danger delete-article" data-id="{{ScriptTitle.id}}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
    </table>
    {% else %}
        <p> No data to display. </p>
{% endif %}
{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}